# Generated by Django 4.2.5 on 2023-10-20 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default='9469637d-22df-49d2-9cb0-0f2a586d9dc0', editable=False, max_length=100)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete'), ('Overdue', 'Overdue')], default='To Do', max_length=11)),
                ('task', models.CharField(max_length=30)),
                ('description', models.CharField(default='insert description', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deadline', models.DateTimeField()),
                ('priority', models.CharField(choices=[('1', 'Highest'), ('2', 'High'), ('3', 'Medium'), ('4', 'Low'), ('5', 'Lowest')], default=2, max_length=7)),
                ('notifications', models.CharField(choices=[('None', 'None'), ('Desktop Only', 'Desktop Only'), ('Email Only', 'Email Only'), ('Both', 'Both')], default='None', max_length=12)),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
