# Generated by Django 4.2.5 on 2023-10-14 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('task', models.CharField(max_length=30)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('124378fd-f3c4-471a-9df8-f032ca0ad363'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
